//--------------------------------------------------------------------------------
// Auto-generated by Migen (--------) & LiteX (2c4b8963) on 2020-03-18 23:37:23
//--------------------------------------------------------------------------------
#ifndef __GENERATED_MEM_H
#define __GENERATED_MEM_H

#define CSR_BASE 0x00000000L
#define CSR_SIZE 0x00010000

#define MMAP_BASE 0x00020000L
#define MMAP_SIZE 0x00020000

#endif
