//--------------------------------------------------------------------------------
// Auto-generated by Migen (--------) & LiteX (2c4b8963) on 2020-03-18 23:37:23
//--------------------------------------------------------------------------------
#ifndef __GENERATED_SOC_H
#define __GENERATED_SOC_H
#define CONFIG_CLOCK_FREQUENCY 125000000
#define CONFIG_CPU_TYPE_NONE
#define CONFIG_CPU_VARIANT_STANDARD
#define CONFIG_CSR_DATA_WIDTH 32
#define CONFIG_CSR_ALIGNMENT 32
#define DMA_CHANNELS 4
#define PCIE_DMA0_READER_INTERRUPT 0
#define PCIE_DMA0_WRITER_INTERRUPT 1
#define PCIE_DMA1_READER_INTERRUPT 2
#define PCIE_DMA1_WRITER_INTERRUPT 3
#define PCIE_DMA2_READER_INTERRUPT 4
#define PCIE_DMA2_WRITER_INTERRUPT 5
#define PCIE_DMA3_READER_INTERRUPT 6
#define PCIE_DMA3_WRITER_INTERRUPT 7

#endif
